#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$1" == "-?" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Intialize cluster-level resources

SYNOPSIS
   $EXECUTABLE wan1|wan2 [storage_class] [-?]

DESCRIPTION
   Intializes cluster-level resources as follows:
   
   - Configure NetworkPolicy for '$PROJECT_WAN1' and '$PROJECT_WAN2'.
   - Apply CustomResourceDefinition
   - Apply ClusterRole for Hazelcast operator and Hazelcast. 

SEE ALSO
   cluster/

EOF
exit
fi

oc label namespace $PROJECT_WAN1 hazelcast=true
oc label namespace $PROJECT_WAN2 hazelcast=true

oc create -f $APP_DIR/cluster/wan1-netpol.yaml
oc create -f $APP_DIR/cluster/wan2-netpol.yaml

oc apply -f $APP_DIR/cluster/hazelcastcluster.crd.yaml
oc apply -f $APP_DIR/cluster/operator-rbac.yaml
oc apply -f $APP_DIR/cluster/hazelcast-rbac.yaml
