#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Delete all resources

SYNOPSIS
   $EXECUTABLE wan1|wan2 [-all] [-?]

DESCRIPTION
   Deletes all but persistent claim resources. To delete pvc, pv, and storage, specify the '-all' option.

OPTIONS
   wan1|wan2
             This option is required. 'wan1' cleans up resources in the '$PROJECT_WAN1' project and 
             'wan2' cleans up resources in the '$PROJECT_WAN2' project.

   -all
             If specified then it also deletes pvc, pv, and storage.

EOF
exit
fi

WAN=$1
if [ "$WAN" != "wan1" ] && [ "$WAN" != "wan2" ]; then
   echo >&2 "ERROR: Invalid input: [$WAN]. Please enter wan1 or wan2."
   exit 1
fi

if [ "$WAN" == "wan1" ]; then
   NAMESPACE=$PROJECT_WAN1
else
   NAMESPACE=$PROJECT_WAN2
fi

./stop_padogrid $*
./stop_hazelcast $*
