#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Start the Hazelcast OpenShift operator and a Hazelcast cluster

SYNOPSIS
   $EXECUTABLE wan1|wan2 [-?]

DESCRIPTION
   Starts the Hazelcast OpenShift operator and a Hazelcast cluster.

OPTIONS
   wan1|wan2
             This option is required. 'wan1' stops Hazelcast in the '$PROJECT_WAN1' project and 
             'wan2' stops Hazelcast in the '$PROJECT_WAN2' project.

SEE ALSO
   wan1/hazelcast/, wan2/hazelast/

EOF
exit
fi

WAN=$1
if [ "$WAN" != "wan1" ] && [ "$WAN" != "wan2" ]; then
   echo >&2 "ERROR: Invalid input: [$WAN]. Please enter wan1 or wan2."
   exit 1
fi

pushd $APP_DIR/$WAN/hazelcast > /dev/null
oc apply -f operator-rbac.yaml
oc apply -f hazelcast-rbac.yaml
oc apply -f hazelcastcluster.crd.yaml
oc apply -f operator-rhel.yaml
oc apply -f secret.yaml
oc apply -f hazelcast.yaml
popd > /dev/null
