#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Delete all resrouces

SYNOPSIS
   $EXECUTABLE [-all] [-?]

DESCRIPTION
   Deletes all Hazelccast resources but the management persistent claim. To delete the persistent claim,
   specify the '-all' option.

EOF
exit
fi

WAN=$1
if [ "$WAN" != "wan1" ] && [ "$WAN" != "wan2" ]; then
   echo >&2 "ERROR: Invalid input: [$WAN]. Please enter wan1 or wan2."
   exit 1
fi

if [ "$WAN" == "wan1" ]; then
   NAMESPACE=$PROJECT_WAN1
else
   NAMESPACE=$PROJECT_WAN2
fi

echo "Deleting Hazelcast resources..."
pushd $APP_DIR/$WAN/hazelcast > /dev/null
oc delete -f hazelcast.yaml
oc delete -f secret.yaml
oc delete -f operator-rhel.yaml
# Patch required. Otherwise, CRD delete will hang.
oc patch --namespace=$NAMESPACE crd/hazelcastenterprises.hazelcast.com -p '{"metadata":{"finalizers":[]}}' --type=merge
oc delete -f hazelcastcluster.crd.yaml
oc delete -f hazelcast-rbac.yaml
oc delete -f operator-rbac.yaml
popd > /dev/null

# Delete the rest if ALL specified
if [ "$ALL" == "true" ]; then
   echo "Deleting pvc..."
   oc delete --namespace=$NAMESPACE pvc mancenter-storage-hz-hazelcast-enterprise-mancenter-0
fi
