apiVersion: hazelcast.com/v1alpha1
kind: HazelcastEnterprise
metadata:
  name: hz
  labels:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator

    # hazelcast and role labels for project-to-project communications via NetworkPolicy
    hazelcast: "true"
    role: hazelcast
  namespace: ${PROJECT_NAMESPACE}
spec:
  hazelcast:
    licenseKeySecretName: hz-license-key-secret
    yaml:
      hazelcast:
        properties:
          hazelcast.phone.home.enabled: false
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
              service-name: ${serviceName}
              namespace: ${namespace}
              resolve-not-ready-addresses: true
          ssl:
            enabled: ${hazelcast.ssl}
          rest-api:
            enabled: true
            endpoint-groups:
              HEALTH_CHECK:
                enabled: true
        hot-restart-persistence:
          enabled: ${hazelcast.hotRestart}
          base-dir: /data/hot-restart
          validation-timeout-seconds: 1200
          data-load-timeout-seconds: 900
          auto-remove-stale-data: true
        management-center:
          enabled: ${hazelcast.mancenter.enabled}
          url: ${hazelcast.mancenter.url}
    # configurationFiles are any additional Hazelcast configuration files
    # configurationFiles:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
  securityContext:
    runAsUser: ""
    fsGroup: ""
  mancenter:
    # javaOpts are additional JAVA_OPTS properties for Hazelcast Management Center
    javaOpts: -Dhazelcast.mc.rest.enabled=true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
              - amd64
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1024Mi
  rbac:
    create: false

  serviceAccount:
    create: false
    name: hazelcast
